### ISSUE TITLE
User guide recommends creating venv with `virtual .venv`

### ISSUE THREAD

**Issue by garryod** [DiamondLightSource/python3-pip-skeleton-cli#50]
The [getting started with your repo](https://diamondlightsource.github.io/python3-pip-skeleton-cli/main/user/tutorials/new.html#getting-started-with-your-new-repo) section of the docs suggests you create a virtual environment with `virtual .venv`. Should this instead be `venv .venv` or `python -m venv .venv`?

**Comment by coretl** [comment]
I'd go for `python -m venv venv`
