### ISSUE TITLE
Documentation on installation requires clarification for zsh

### ISSUE THREAD

**Issue by ConorFWild** [DiamondLightSource/python3-pip-skeleton-cli#52]
zsh uses square brackets for globbing, hence the command:
`bash
pip install .[dev]
`
in https://diamondlightsource.github.io/python3-pip-skeleton-cli/main/user/tutorials/new.html#getting-started-with-your-new-repo will fail with the error:
`bash
zsh: no matches found: .[dev]
`

The correct command is instead:
`bash
pip install '.[dev]'
`

This could/should use flagging as a possiblity in the documentation?

**Comment by gilesknap** [comment]
Thanks - will fix this.

**Comment by gilesknap** [comment]
assigning to Eva to roll in with other docs changes.
