### ISSUE TITLE
Documentation on creating a new repo requires clarification on venv suggested location and dev

### ISSUE THREAD

**Issue by ConorFWild** [DiamondLightSource/python3-pip-skeleton-cli#53]
It is inclear that documentation in https://diamondlightsource.github.io/python3-pip-skeleton-cli/main/user/tutorials/new.html#getting-started-with-your-new-repo is reccomending creating the venv in the new directory created by the cli, or that the pip command should be run from that directory.

`bash
virtual .venv
source .venv/bin/activate
pip install -e .[dev]
`

Furthermore the documentation elsewhere prefers 
`bash
python3 -m pip install
`
to
`pip install`

Is there a reason for the difference?

**Comment by gilesknap** [comment]
``python3 -m pip install`` is what we should be using.
I'll make sure the docs are consistent on this.

**Comment by GDYendell** [comment]
There is some discussion of this here: https://snarky.ca/why-you-should-use-python-m-pip/

I am not convinced by the arguments, but `python -m ...` is the convention so happy to do that.
