### ISSUE TITLE
Documentation reccomendations for anaconda usage

### ISSUE THREAD

**Issue by ConorFWild** [DiamondLightSource/python3-pip-skeleton-cli#54]
The documentation reccomends virtual enviroments, which can be used as described in https://diamondlightsource.github.io/python3-pip-skeleton-cli/main/user/tutorials/installation.html and https://diamondlightsource.github.io/python3-pip-skeleton-cli/main/user/tutorials/new.html from inside an anaconda enviroment (such as the base enviroment that is default for most people with an anaconda install), but perhaps it would be good for the documentation to give suggestions for creating an anaconda enviroment for development rather than a virtual enviroment? Or at least reccomendations on deactivating any active anaconda enviroment before sourcing the newly created venv?

**Comment by gilesknap** [comment]
@garryod could you comment on this one please?

**Comment by garryod** [comment]
As I understand it, there are numerous issues which may arise when developing standards-based applications within a conda environment, as such I believe our recommendation would be to deactivate any conda environment which may be active before activating the venv. As `module load python` within Diamond activates a conda environment it seems wise to recommend deactivating this before activating the venv in both of the linked pages. I will submit a PR which adds such a recommendation
