### ISSUE TITLE
Add instructions to automatically install pre-commit

### ISSUE THREAD

**Issue by AlexanderWells-diamond** [DiamondLightSource/python3-pip-skeleton-cli#67]
Currently it is a manual step to install `pre-commit`, and it is only documented in `how-to/Run linting using pre-commit`. 

The pre-commit webpage suggests a mechanism to automatically enable `pre-commit` on newly cloned repos: https://pre-commit.com/#automatically-enabling-pre-commit-on-repositories

It appears to still be a per-person configuration, but some notes in the documentation means each person will only need to run it once and will then always get `pre-commit` on new repos.

It may also be a good idea to include installing the pre-commit in `tutorials/Creating a new repo from the skeleton` and `how-to/How to adopt the skeleton in an existing repo`, as it is otherwise not obvious and the checks would only run in CI.

**Comment by gilesknap** [comment]
I agree.

@evalott100 would you be able to add this?
