### ISSUE TITLE
Add windows and mac to matrix in python3-pip-skeleton-cli

### ISSUE THREAD

**Issue by coretl** [DiamondLightSource/python3-pip-skeleton-cli#81]
We don't want this in the skeleton itself (not common to need it), but it would be good to have a canary in case we put linux paths in (like the coverage data one)

**Comment by evalott100** [comment]
@coretl #84  (the PR for this) is running on windows and macos runners. We seem to have failures in the test themselves (e.g file format errors for windows).

When I find the time after bluesky stuff, should I convert the skeleton to work with macos and windows?

**Comment by coretl** [comment]
Yes please, can you also restore `test_boilerplate_removed.py` (from python3-pip-skeleton) in this repo, that's something we want to make sure works on windows and mac too.
